/*    */ package com.google.inject.internal;
/*    */ 
/*    */ public enum ErrorId
/*    */ {
/*  5 */   AMBIGUOUS_TYPE_CONVERSION,
/*  6 */   AOP_DISABLED,
/*  7 */   AT_INJECT_REQUIRED,
/*  8 */   AT_TARGET_IS_MISSING_PARAMETER,
/*  9 */   BINDING_ALREADY_SET,
/* 10 */   BINDING_TO_GUICE_TYPE,
/* 11 */   BINDING_TO_PROVIDER,
/* 12 */   CAN_NOT_PROXY_CLASS,
/* 13 */   CHILD_BINDING_ALREADY_SET,
/* 14 */   CIRCULAR_PROXY_DISABLED,
/* 15 */   CONSTRUCTOR_NOT_DEFINED_BY_TYPE,
/* 16 */   CONVERSION_TYPE_ERROR,
/* 17 */   CONVERTER_RETURNED_NULL,
/* 18 */   DUPLICATE_BINDING_ANNOTATIONS,
/* 19 */   DUPLICATE_ELEMENT,
/* 20 */   DUPLICATE_MAP_KEY,
/* 21 */   DUPLICATE_SCOPES,
/* 22 */   DUPLICATE_SCOPE_ANNOTATIONS,
/* 23 */   ERROR_ENHANCING_CLASS,
/* 24 */   ERROR_INJECTING_CONSTRUCTOR,
/* 25 */   ERROR_INJECTING_METHOD,
/* 26 */   ERROR_IN_CUSTOM_PROVIDER,
/* 27 */   ERROR_IN_USER_CODE,
/* 28 */   ERROR_IN_USER_INJECTOR,
/* 29 */   ERROR_NOTIFYING_TYPE_LISTENER,
/* 30 */   EXPOSED_BUT_NOT_BOUND,
/* 31 */   INJECT_ABSTRACT_METHOD,
/* 32 */   INJECT_FINAL_FIELD,
/* 33 */   INJECT_INNER_CLASS,
/* 34 */   INJECT_METHOD_WITH_TYPE_PARAMETER,
/* 35 */   INJECT_RAW_MEMBERS_INJECTOR,
/* 36 */   INJECT_RAW_PROVIDER,
/* 37 */   INJECT_RAW_TYPE_LITERAL,
/* 38 */   JIT_BINDING_ALREADY_SET,
/* 39 */   JIT_DISABLED,
/* 40 */   JIT_DISABLED_IN_PARENT,
/* 41 */   KEY_NOT_FULLY_SPECIFIED,
/* 42 */   MISPLACED_BINDING_ANNOTATION,
/* 43 */   MISSING_CONSTANT_VALUES,
/* 44 */   MISSING_CONSTRUCTOR,
/* 45 */   MISSING_IMPLEMENTATION,
/* 46 */   MISSING_RUNTIME_RETENTION,
/* 47 */   MISSING_SCOPE_ANNOTATION,
/* 48 */   NOT_A_SUBTYPE,
/* 49 */   NULL_ELEMENT_IN_SET,
/* 50 */   NULL_INJECTED_INTO_NON_NULLABLE,
/* 51 */   NULL_VALUE_IN_MAP,
/* 52 */   OPTIONAL_CONSTRUCTOR,
/* 53 */   RECURSIVE_BINDING,
/* 54 */   RECURSIVE_IMPLEMENTATION_TYPE,
/* 55 */   RECURSIVE_PROVIDER_TYPE,
/* 56 */   SCOPE_ANNOTATION_ON_ABSTRACT_TYPE,
/* 57 */   SCOPE_NOT_FOUND,
/* 58 */   STATIC_INJECTION_ON_INTERFACE,
/* 59 */   SUBTYPE_NOT_PROVIDED,
/* 60 */   TOO_MANY_CONSTRUCTORS,
/* 61 */   VOID_PROVIDER_METHOD,
/*    */ 
/*    */   
/* 64 */   OTHER;
/*    */ }


/* Location:              C:\Users\vovanchik\Downloads\TLauncher.jar!\com\google\inject\internal\ErrorId.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */